name: Make release
run-name: Creating release ${{ github.ref_name }}
on:
  push:
    tags:
      - '*'
jobs:
  build-backend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [amd64, arm64, armv7]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25

      - name: Set GOARCH/GOOS
        run: |
          case ${{ matrix.platform }} in
            amd64)
              echo "GOARCH=amd64" >> $GITHUB_ENV
              ;;
            arm64)
              echo "GOARCH=arm64" >> $GITHUB_ENV
              ;;
            armv7)
              echo "GOARCH=arm" >> $GITHUB_ENV
              ;;
          esac
          echo "GOOS=linux" >> $GITHUB_ENV

      - name: Build backend
        working-directory: ./backend
        run: go build -v -o ./mikochi .

      - name: Upload backend
        uses: actions/upload-artifact@v4
        with:
          name: backend-build-${{ matrix.platform }}
          path: ./backend/mikochi

  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        run: npm ci
        working-directory: frontend

      - name: Build frontend
        run: npm run build
        working-directory: frontend

      - name: Upload frontend
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: ./frontend/dist/

  release-docker:
    needs: [build-backend, build-frontend]

    strategy:
      matrix:
        platform: [amd64, arm64, armv7]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Download frontend build
        uses: actions/download-artifact@v7
        with:
          name: frontend-build
          path: ./frontend/dist/

      - name: Download backend build
        uses: actions/download-artifact@v7
        with:
          name: backend-build-${{ matrix.platform }}
          path: ./backend

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU for docker
        uses: docker/setup-qemu-action@v2

      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/${{ matrix.platform == 'amd64' && 'amd64' || matrix.platform == 'arm64' && 'arm64' || 'arm/v7' }}
          push: true
          tags: |
            zer0tonin/mikochi:latest-${{ matrix.platform }}
            zer0tonin/mikochi:${{ github.ref_name }}-${{ matrix.platform }}

  create-multiarch-manifest:
    needs: [release-docker]

    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create and Push Multi-Arch Manifest for Version Tag
        run: |
          docker buildx imagetools create \
            -t "zer0tonin/mikochi:${{ github.ref_name }}" \
            "zer0tonin/mikochi:${{ github.ref_name }}-amd64" \
            "zer0tonin/mikochi:${{ github.ref_name }}-arm64" \
            "zer0tonin/mikochi:${{ github.ref_name }}-armv7"

      - name: Create and Push Multi-Arch Manifest for Latest Tag
        run: |
          docker buildx imagetools create \
            -t "zer0tonin/mikochi:latest" \
            "zer0tonin/mikochi:latest-amd64" \
            "zer0tonin/mikochi:latest-arm64" \
            "zer0tonin/mikochi:latest-armv7"

  release-github:
    needs: [build-backend, build-frontend]

    runs-on: ubuntu-latest

    outputs:
      release_id: ${{ steps.create_release.outputs.id }}

    steps:
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

  upload-tar:
    needs: [release-github]

    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [amd64, arm64, armv7]

    steps:
      - name: Download frontend build
        uses: actions/download-artifact@v7
        with:
          name: frontend-build
          path: ./frontend/dist/

      - name: Download backend build
        uses: actions/download-artifact@v7
        with:
          name: backend-build-${{ matrix.platform }}
          path: ./backend

      - name: Create tar.gz archives
        run: |
          mkdir -p release-files
          mkdir -p temp-release/mikochi-${{ github.ref_name }}/
          mkdir -p temp-release/mikochi-${{ github.ref_name }}/static
          cp backend/mikochi temp-release/mikochi-${{ github.ref_name }}/mikochi
          chmod 755 temp-release/mikochi-${{ github.ref_name }}/mikochi
          cp -r frontend/dist/* temp-release/mikochi-${{ github.ref_name }}/static
          tar -czf "release-files/mikochi-${{ github.ref_name }}-linux-${{ matrix.platform }}.tar.gz" -C temp-release .
          rm -rf temp-release/mikochi-${{ github.ref_name }}/

      - name: Upload tar.gz builds to release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          RELEASE_ID=${{ needs.release-github.outputs.release_id }}
          FILE="release-files/mikochi-${{ github.ref_name }}-linux-${{ matrix.platform }}.tar.gz"
          echo "Uploading $FILE"
          curl -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Content-Type: application/gzip" \
            --data-binary @"$FILE" \
            "https://uploads.github.com/repos/${{ github.repository}}/releases/$RELEASE_ID/assets?name=$(basename "$FILE")"

  upload-deb:
    needs: [release-github]

    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [amd64, arm64, armv7]

    steps:
      - name: Download frontend build
        uses: actions/download-artifact@v7
        with:
          name: frontend-build
          path: ./frontend/dist/

      - name: Download backend build
        uses: actions/download-artifact@v7
        with:
          name: backend-build-${{ matrix.platform }}
          path: ./backend

      - name: Set DEBARCH
        run: |
          case ${{ matrix.platform }} in
            amd64)
              echo "DEBARCH=amd64" >> $GITHUB_ENV
              ;;
            arm64)
              echo "DEBARCH=arm64" >> $GITHUB_ENV
              ;;
            armv7)
              echo "DEBARCH=armhf" >> $GITHUB_ENV
              ;;
          esac

      - name: Create directory structure
        run: |
          mkdir -p deb-package/mikochi-${{ github.ref_name }}-linux-${{ matrix.platform }}/usr/bin
          mkdir -p deb-package/mikochi-${{ github.ref_name }}-linux-${{ matrix.platform }}/usr/share/mikochi/static
          mkdir -p deb-package/mikochi-${{ github.ref_name }}-linux-${{ matrix.platform }}/DEBIAN

      - name: Copy files
        run: |
          cp backend/mikochi deb-package/mikochi-${{ github.ref_name }}-linux-${{ matrix.platform }}/usr/bin/
          chmod 755 deb-package/mikochi-${{ github.ref_name }}-linux-${{ matrix.platform }}/usr/bin/mikochi
          cp -r frontend/dist/* deb-package/mikochi-${{ github.ref_name }}-linux-${{ matrix.platform }}/usr/share/mikochi/static/

      - name: Create control file
        run: |
          cat > deb-package/mikochi-${{ github.ref_name }}-linux-${{ matrix.platform }}/DEBIAN/control << EOF
          Package: mikochi
          Version: ${{ github.ref_name }}
          Section: web
          Priority: optional
          Architecture: $DEBARCH
          Depends: libc6
          Maintainer: Alice Girard Guittard <hi@alicegg.tech>
          Description: Mikochi - A minimalist remote file browser
          EOF

      - name: Build DEB package
        run: |
          mkdir -p release-files
          dpkg-deb --build deb-package/mikochi-${{ github.ref_name }}-linux-${{ matrix.platform }} release-files/mikochi-${{ github.ref_name }}-linux-${{ matrix.platform }}.deb

      - name: Upload deb builds to release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          RELEASE_ID=${{ needs.release-github.outputs.release_id }}
          FILE="release-files/mikochi-${{ github.ref_name }}-linux-${{ matrix.platform }}.deb"
          echo "Uploading $FILE"
          curl -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @"$FILE" \
            "https://uploads.github.com/repos/${{ github.repository}}/releases/$RELEASE_ID/assets?name=$(basename "$FILE")"

  upload-rpm:
    needs: [release-github]

    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [amd64, arm64, armv7]

    steps:
      - name: Download frontend build
        uses: actions/download-artifact@v7
        with:
          name: frontend-build
          path: ./frontend/dist/

      - name: Download backend build
        uses: actions/download-artifact@v7
        with:
          name: backend-build-${{ matrix.platform }}
          path: ./backend

      - name: Set RPMARCH
        run: |
          case ${{ matrix.platform }} in
            amd64)
              echo "RPMARCH=x86_64" >> $GITHUB_ENV
              ;;
            arm64)
              echo "RPMARCH=aarch64" >> $GITHUB_ENV
              ;;
            armv7)
              echo "RPMARCH=armv7hl" >> $GITHUB_ENV
              ;;
          esac

      - name: Create directory structure
        run: |
          mkdir -p \
            rpm-package/BUILD \
            rpm-package/BUILDROOT \
            rpm-package/RPMS \
            rpm-package/SOURCES \
            rpm-package/SPECS \
            rpm-package/SRPMS \
            rpm-package/BUILDROOT/mikochi-${{ github.ref_name }}-1.$RPMARCH/usr/bin \
            rpm-package/BUILDROOT/mikochi-${{ github.ref_name }}-1.$RPMARCH/usr/share/mikochi/static

      - name: Copy files
        run: |
          cp backend/mikochi rpm-package/BUILDROOT/mikochi-${{ github.ref_name }}-1.$RPMARCH/usr/bin
          chmod 755 rpm-package/BUILDROOT/mikochi-${{ github.ref_name }}-1.$RPMARCH/usr/bin/mikochi
          cp -r frontend/dist/* rpm-package/BUILDROOT/mikochi-${{ github.ref_name }}-1.$RPMARCH/usr/share/mikochi/static

      - name: Create spec file
        run: |
          cat > rpm-package/SPECS/mikochi.spec << EOF
          Name: mikochi
          Version: ${{ github.ref_name }}
          Release: 1
          Summary: Mikochi - A minimalist remote file browser
          License: MIT
          %description
          Mikochi - A minimalist remote file browser
          %prep
          # Nothing to prepare
          %build
          # Nothing to build
          %install
          # Files are pre-copied to BUILDROOT by the workflow script
          %files
          /usr/bin/mikochi
          /usr/share/mikochi/static/*
          %changelog
          # N/A
          EOF

      - name: Build RPM package
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm
          rpmbuild --target $RPMARCH-redhat-linux --define "_topdir $(pwd)/rpm-package" -bb rpm-package/SPECS/mikochi.spec
          mkdir -p release-files
          cp rpm-package/RPMS/$RPMARCH/mikochi-${{ github.ref_name }}-1.$RPMARCH.rpm release-files/mikochi-${{ github.ref_name }}-linux-${{ matrix.platform }}.rpm

      - name: Upload deb builds to release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          RELEASE_ID=${{ needs.release-github.outputs.release_id }}
          FILE="release-files/mikochi-${{ github.ref_name }}-linux-${{ matrix.platform }}.rpm"
          echo "Uploading $FILE"
          curl -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @"$FILE" \
            "https://uploads.github.com/repos/${{ github.repository}}/releases/$RELEASE_ID/assets?name=$(basename "$FILE")"
